2019P4RazorPagesBasics/ViewModels/CalcData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace RazorPagesBasics.ViewModels
{
    public enum Operation
    {   
        [Display(Name = "součet")]
        sum = 1,
        rozdíl,
        součin,
        podíl
    }
    public class CalcData
    {
        [Display(Name = "První číslo")]
        public int A { get; set; }

        [Display(Name = "Druhé číslo")]
        [Range(1, 100, ErrorMessage = "Zadej jen číslo od {1} do {2}")]
        public int B { get; set; }

        [Display(Name = "Operace")]
        public Operation Op { get; set; }
    }
}

2019P4RazorPagesBasics/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesBasics.ViewModels;

namespace RazorPagesBasics.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public CalcData Data { get; set; }

        public string Result { get; set; }

        public void OnGet()
        {
            
            //Data = new CalcData() { A = 12, B = 33 };
        }

        public void OnGetOther(CalcData c)
        {
            Data = new CalcData() { A = 44, B = 66 };
        }

        public void OnGetForced(int a, int b)
        {
            Data = new CalcData() { A = a, B = b };
        }

        private int Calculate(int A, int B, Operation op)
        {
            if (op == Operation.sum) return A + B;
            if (op == Operation.rozdíl) return A - B;
            if (op == Operation.podíl) return A / B;
            return A * B;
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                //data v public CalcData Data { get; set; } jsou OK

                Result = $"{Data.A} {Data.Op} {Data.B} = {Calculate(Data.A, Data.B, Data.Op)}";

            }

            return Page();
        }
    }
}

2019P4RazorPagesBasics/Pages/Index.cshtml
@page
@model Pages.IndexModel
@{
    ViewData["Title"] = "Calc HomePage";
}

<h1>Kalkulátor v0.0.1</h1>

<form method="post">
    <label asp-for="Data.A"></label>
    <input asp-for="Data.A" />

    <label asp-for="Data.Op"></label>
    <select asp-for="Data.Op" asp-items="Html.GetEnumSelectList<Operation>()"></select>

    <label asp-for="Data.B"></label>
    <input asp-for="Data.B" />
    <span asp-validation-for="Data.B"></span>
    <input type="submit" value="Počítej!" />
</form>

<div>
    <ul>
        <li><a asp-page="./Index" asp-page-handler="Forced" asp-route-a="666" asp-route-b="333">a=666 b=333</a></li>
        <li><a asp-route-a="999" asp-route-b="333">a=999 b=333</a></li>
        <li><a asp-page-handler="Forced" asp-route-a="111" asp-route-b="333">a=111 b=333</a></li>
    </ul>
</div>

<div>
    @if (Model.Result?.Length > 0)
    {
        <h2>Výsledek</h2>
        <p>@Model.Result</p>
    }
</div>

2019P4RazorPagesBasics/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@(ViewBag.Title)</title>
</head>
<body>
    <div>
        @(RenderBody())
    </div>
</body>
</html>