2019P4RazorPagesLogikSession/ViewModels/LogikInit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Logik.ViewModels
{
    public class LogikInit
    {
        [Display(Name = "From number")]
        [Range(1, 100, ErrorMessage = "Only number from {1} to {2}")]
        public int From { get; set; }

        [Display(Name = "To number")]
        [Range(1, 10000, ErrorMessage = "Only number from {1} to {2}")]
        public int To { get; set; }
    }
}

2019P4RazorPagesLogikSession/ViewModels/LogikS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Logik.ViewModels
{
    public class LogikS
    {
        [Display(Name = "Enter Your Try")]
        public int LastTry { get; set; }
    }
}

2019P4RazorPagesLogikSession/Pages/Game.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Logik.ViewModels;
using Logik.Services;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Logik.Pages
{
    public class GameModel : PageModel
    {
        private static readonly Random rnd = new Random();

        readonly ISessionController<LogicGame> logicgame;
        readonly LogicGame logic;
        public GameModel(ISessionController<LogicGame> logicgame)
        {
            this.logic = logicgame.LoadOrCreate(LogicGameKey.Key);
            this.logicgame = logicgame;
            refreshOptionsList();
        }

        private void refreshOptionsList()
        {
            OptionsList = new List<SelectListItem>();
            for (int i = logic.Min; i <= logic.Max; i++)
            {
                if ((logic.Max - logic.Min) / 2 == i)
                    OptionsList.Add(new SelectListItem(i.ToString(), i.ToString(), true));
                else
                    OptionsList.Add(new SelectListItem(i.ToString(), i.ToString()));
            }
        }

        [BindProperty]
        public LogikS LogikData { get; set; }

        //zobrazované vlastnosti
        public string AlertClass
        {
            get
            {
                if (logic.SecretToLastTry > 0) { return "primary"; }
                if (logic.SecretToLastTry < 0) { return "danger"; }
                return "success";
            }
        }
        public List<SelectListItem> OptionsList { get; set; }
        public bool IsRunning => logic.GameStatus == GameStatus.Running;
        public bool IsVictory => logic.GameStatus == GameStatus.Victory;
        public int Round => logic.Round;
        public int Secret => logic.Secret ?? -999;
        public string RoundStr => logic.RoundStr;

        [TempData]
        public string Message { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                logic.Try(LogikData.LastTry);
                Message = logic.GetMessage();
                logicgame.Save(LogicGameKey.Key, logic);
                refreshOptionsList();
                RedirectToPage();
            }
            return Page();
        }
    }
}

2019P4RazorPagesLogikSession/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Logik.ViewModels;
using Logik.Services;

namespace Logik.Pages
{
    public class IndexModel : PageModel
    {
        readonly ISessionController<LogicGame> logicgame;
        readonly LogicGame logic;
        public IndexModel(ISessionController<LogicGame> logicgame)
        {
            this.logic = logicgame.LoadOrCreate(LogicGameKey.Key);
            this.logicgame = logicgame;
        }

        [BindProperty]
        public LogikInit FromTo { get; set; }

        public void OnGet()
        {
            FromTo = new LogikInit() { From = 1, To = 5 };
        }

        public void OnGetRange(int from, int to)
        {
            FromTo = new LogikInit() { From = from, To = to };
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                logic.StartGame(FromTo.From, FromTo.To);
                logicgame.Save(LogicGameKey.Key, logic);
                return RedirectToPage("./Game");
            }
            return Page();
        }
    }
}

2019P4RazorPagesLogikSession/Pages/Game.cshtml
@page
@model GameModel
@{
    ViewData["Title"] = "Game";
}
    <h2>Game @{if (!Model.IsRunning) {<span>not</span>} } running...</h2>

@if (Model.IsRunning)
{
    <form method="post">
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label>Round no.</label>
                    <input value="@Model.Round" class="form-control" readonly />
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="LogikData.LastTry"></label>
                    <select asp-for="LogikData.LastTry" asp-items="@Model.OptionsList" class="form-control">
                    </select>
                    <span asp-validation-for="LogikData.LastTry" class="form-text text-danger"></span>
                </div>
            </div>
            <div class="col-sm-2 align-self-center flex-grow-1">
                <button type="submit" class="btn btn-primary w-100">Try!</button>
            </div>
        </div>
    </form>
}

@if (Model.IsVictory)
{
    <div class="jumbotron">
        <p class="text-success">Secret @Model.Secret was resolved on @Model.RoundStr attempt.</p>
    </div>
}

@if (TempData["Message"] != null)
{
    <p class="alert alert-@Model.AlertClass mt-2">
        @TempData.Peek("Message")
    </p>
}

@if (!Model.IsRunning)
{
    <p><a asp-page="Index" class="btn btn-info">New Game</a></p>
}

2019P4RazorPagesLogikSession/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Index";
}

    <h2>game initialization</h2>
    <form method="post">
        <div class="row">
            <div class="col-sm-5 form-group">
                <label asp-for="FromTo.From"></label>
                <input asp-for="FromTo.From" class="form-control" />
                <span asp-validation-for="FromTo.From" class="form-text text-danger"></span>
            </div>
            <div class="col-sm-5 form-group">
                <label asp-for="FromTo.To"></label>
                <input asp-for="FromTo.To" class="form-control" />
                <span asp-validation-for="FromTo.To" class="form-text text-danger"></span>
            </div>
            <div class="col-sm-2 align-self-center">
                <button type="submit" class="btn btn-primary">Start the Game</button>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <div class="col-sm-6">
                    <div class="list-group">
                        <a asp-route-from="1" asp-route-to="10" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 10</a>
                        <a asp-route-from="1" asp-route-to="20" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 20</a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="list-group">
                        <a asp-route-from="1" asp-route-to="50" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 50</a>
                        <a asp-route-from="1" asp-route-to="100" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 100</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="list-group">
                <a asp-route-from="1" asp-route-to="500" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 500</a>
                <a asp-route-from="1" asp-route-to="1000" asp-page-handler="range" class="list-group-item list-group-item-action">from 1 to 1000</a>
            </div>
        </div>
    </div>

2019P4RazorPagesLogikSession/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h1 class="h3">Logik Simple &ndash; The Game</h1>
        <div>
            @RenderBody()
        </div>
    </div>
</body>
</html>